name: Trigger auto deployment for swiftfiddle-runner-functions-514

# When this action will be executed
on:
  # Automatically trigger it when detected changes in repo
  push:
    branches: [main]
    paths:
      - "**"
      - ".github/workflows/swiftfiddle-runner-functions-514-AutoDeployTrigger-974a6edc-d286-428c-8141-ae6efd47e7e8.yml"

  # Allow manual trigger
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout to the branch
        uses: actions/checkout@v4

      - name: Azure Login
        uses: azure/login@v1
        with:
          creds: ${{ secrets.SWIFTFIDDLERUNNERFUNCTIONS514_AZURE_CREDENTIALS }}

      - name: Build and push container image to registry
        uses: azure/container-apps-deploy-action@v1
        with:
          appSourcePath: ${{ github.workspace }}
          registryUrl: swiftfiddle.azurecr.io
          registryUsername: ${{ secrets.SWIFTFIDDLERUNNERFUNCTIONS514_REGISTRY_USERNAME }}
          registryPassword: ${{ secrets.SWIFTFIDDLERUNNERFUNCTIONS514_REGISTRY_PASSWORD }}
          containerAppName: swiftfiddle-runner-functions-514
          resourceGroup: swiftfiddle
          imageToBuild: swiftfiddle.azurecr.io/swiftfiddle-runner-functions-514:latest
